# which benchmarks to run
benchmarks = '../../bril/benchmarks/**/*.bril'
# benchmarks = '../../bril/examples/test/tdce/*.bril'
# how to extract the performance metric from stderr
extract = 'total_dyn_inst: (\d+)'

[runs.baseline]
pipeline = [
  "bril2json",
  "brili -p {args}",
]

[runs.liveness]
pipeline = [
  "bril2json",
  "python3 liveness.py",
  "brili -p {args}",
]
