benchmarks = '../../bril/benchmarks/**/*.bril'
extract = 'total_dyn_inst: (\d+)'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}"
]

[runs.dce]
pipeline = [
    "bril2json",
    "python3 gdce.py"
    "brili -p {args}"
]
